version: '3'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=tenant_db
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - .:/var/www
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
